app/app.py
from flask import Flask
from config import Configuration

from posts.blueprint import posts 

app = Flask(__name__)
app.config.from_object(Configuration)

app.register_blueprint(posts, url_prefix='/blog')

app/main.py
from app import app
import viev
if __name__ == '__main__':
	app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
	return render_template('posts/index.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	<title>
		{% block title %}

		{% endblock %} | Flask app



	</title>
</head>
<body>
	
	<nav class="navbar navbar-expand-lg navbar-green bg-dark">
		<div class="container-fluid" >
			<a class="navbar-brand" ref="#" href=" {{ url_for('index') }} ">Flask</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="#">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href=" {{ url_for('posts.index') }} ">Blog</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Dropdown
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="#">Action</a></li>
							<li><a class="dropdown-item" href="#">Another action</a></li>
							<li><hr class="dropdown-divider"></li>
							<li><a class="dropdown-item" href="#">Something else here</a></li>
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link disabled">Disabled</a>
					</li>
				</ul>
				<form class="d-flex">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success" type="submit">Search</button>
				</form>
			</div>
		</div>
	</nav>

	<div class="container">
		<div class="row">
			<h1>
				{% block content_title %}

				{% endblock %} 
				

			</h1>

				{% block content %}

				{% endblock %} 
		</div>
	</div>


<p>
	all
</p>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}
	
	Index page

{% endblock %} 

{% block content_title %}
	
	Index page

{% endblock %} 


{% block content %}
	
	Some content

{% endblock %} 